# Generated by Django 4.1.13 on 2024-06-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiwriteModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254)),
                ("diarytitle", models.CharField(default="제목", max_length=100)),
                ("emotion", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True, null=True)),
                ("place", models.CharField(default="Unknown", max_length=100)),
                (
                    "image_file",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="videos/"),
                ),
                (
                    "sticker_file",
                    models.ImageField(blank=True, null=True, upload_to="stickers"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("withfriend", models.CharField(blank=True, max_length=100, null=True)),
                ("unique_diary_id", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
