# Generated by Django 4.1.13 on 2024-07-03 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diaryapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagemodel",
            name="image_file_url",
        ),
    ]
