# Generated by Django 4.1.13 on 2024-07-02 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diaryapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiwritemodel",
            name="images",
            field=models.ManyToManyField(
                related_name="aiwrite_images", to="diaryapp.imagemodel"
            ),
        ),
    ]
