# Generated by Django 4.1.13 on 2024-07-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diaryapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiwritemodel",
            name="emotion",
            field=models.CharField(
                choices=[
                    ("happy", "행복"),
                    ("sad", "슬픔"),
                    ("angry", "화남"),
                    ("annoying", "짜증"),
                ],
                max_length=100,
            ),
        ),
    ]
