# Generated by Django 4.1.13 on 2024-07-03 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("diaryapp", "0002_remove_imagemodel_image_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemodel",
            name="is_representative",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="aiwritemodel",
            name="representative_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="diaryapp.imagemodel",
            ),
        ),
    ]
