# # Generated by Django 4.1.13 on 2024-07-21 09:33
#
# from django.db import migrations, models
# import django.db.models.deletion
# import uuid
#
#
# def populate_category_codes(apps, schema_editor):
#     Badge = apps.get_model('diaryapp', 'Badge')
#     CategoryCode1 = apps.get_model('diaryapp', 'CategoryCode1')
#     CategoryCode3 = apps.get_model('diaryapp', 'CategoryCode3')
#
#     for badge in Badge.objects.all():
#         # categoryCode1_code 값으로 CategoryCode1 객체 찾기
#         category1 = CategoryCode1.objects.filter(code=badge.categoryCode1_code).first()
#         if category1:
#             # categoryCode1 필드 업데이트
#             badge.categoryCode1 = category1
#
#         # categoryCode3_code 값으로 CategoryCode3 객체 찾기
#         category3 = CategoryCode3.objects.filter(code=badge.categoryCode3_code).first()
#         if category3:
#             # categoryCode3 필드 업데이트
#             badge.categoryCode3 = category3
#
#         # Badge 객체 저장 (변경 사항 저장)
#         badge.save()
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('diaryapp', '0004_commentmodel_diary_id'),
#     ]
#
#     operations = [
#         migrations.CreateModel(
#             name='Badge',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('badge_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
#                 ('name', models.CharField(max_length=255)),
#                 ('badge', models.BinaryField()),
#             ],
#             options={
#                 'db_table': 'diaryapp_badge',
#             },
#         ),
#         migrations.CreateModel(
#             name='CategoryCode1',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('code', models.CharField(max_length=50, unique=True)),
#                 ('name', models.CharField(max_length=255)),
#                 ('rnum', models.IntegerField()),
#             ],
#             options={
#                 'db_table': 'categoryCode1',
#             },
#         ),
#         migrations.CreateModel(
#             name='CategoryCode3',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('code', models.CharField(max_length=50, unique=True)),
#                 ('name', models.CharField(max_length=255)),
#                 ('rnum', models.IntegerField()),
#                 ('cat1_code', models.CharField(max_length=50)),
#                 ('cat2_code', models.CharField(max_length=50)),
#             ],
#             options={
#                 'db_table': 'categoryCode3',
#             },
#         ),
#         migrations.CreateModel(
#             name='Nickname',
#             fields=[
#                 ('nickname_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
#                 ('nickname', models.CharField(max_length=255)),
#                 ('related_title', models.CharField(max_length=255)),
#                 ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nicknames', to='diaryapp.badge')),
#                 ('unique_diary_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nickname', to='diaryapp.aiwritemodel')),
#             ],
#         ),
#         migrations.AddField(
#             model_name='badge',
#             name='categoryCode1',
#             field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category1_badges', to='diaryapp.categorycode1'),
#         ),
#         migrations.AddField(
#             model_name='badge',
#             name='categoryCode3',
#             field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category3_badges', to='diaryapp.categorycode3'),
#         ),
#     ]
